version: '3'
services:

  app:
    restart: unless-stopped
    build:
      context: containers/app/
    ports:
      - 127.0.0.1:${PORT}:80
    networks:
      - app_network

networks:
  app_network:
